-- Snowpitch medallion warehouse (Snowflake)
-- Load data/events.jsonl into BRONZE.RAW_EVENTS(PAYLOAD VARIANT) first.
-- Prefer: PYTHONPATH=. python -m warehouse.snowflake_load

CREATE DATABASE IF NOT EXISTS SNOWPITCH;
CREATE SCHEMA IF NOT EXISTS SNOWPITCH.BRONZE;
CREATE SCHEMA IF NOT EXISTS SNOWPITCH.SILVER;
CREATE SCHEMA IF NOT EXISTS SNOWPITCH.GOLD;

CREATE OR REPLACE TABLE SNOWPITCH.BRONZE.RAW_EVENTS (
    EVENT_ID STRING,
    EVENT_TYPE STRING,
    TS TIMESTAMP_NTZ,
    PLAYER_ID STRING,
    PAYLOAD VARIANT
);

CREATE TABLE IF NOT EXISTS SNOWPITCH.BRONZE.LIVE_CONFIG (
    K STRING,
    V STRING
);

-- High-frequency match state. Separate from RAW_EVENTS so silver/gold
-- event models never pay a VARIANT parse tax on a 100x volume stream.
CREATE TABLE IF NOT EXISTS SNOWPITCH.BRONZE.MATCH_TICKS (
    MATCH_ID STRING,
    TICK_MS NUMBER,
    MINUTE FLOAT,
    BALL_X FLOAT,
    BALL_Y FLOAT,
    BALL_Z FLOAT,
    POSSESSION STRING,
    HOME_GOALS NUMBER,
    AWAY_GOALS NUMBER,
    PHASE STRING,
    MOMENTUM_ON BOOLEAN,
    PATCH STRING,
    PLAYER_ID STRING,
    TS TIMESTAMP_NTZ
);

ALTER TABLE SNOWPITCH.BRONZE.MATCH_TICKS CLUSTER BY (MATCH_ID, TICK_MS);
