-- Snowpitch medallion warehouse (Snowflake)
-- Load data/events.jsonl into BRONZE.RAW_EVENTS(PAYLOAD VARIANT) first.
-- Prefer: PYTHONPATH=. python -m warehouse.snowflake_load

CREATE DATABASE IF NOT EXISTS SNOWPITCH;
CREATE SCHEMA IF NOT EXISTS SNOWPITCH.BRONZE;
CREATE SCHEMA IF NOT EXISTS SNOWPITCH.SILVER;
CREATE SCHEMA IF NOT EXISTS SNOWPITCH.GOLD;

CREATE OR REPLACE TABLE SNOWPITCH.BRONZE.RAW_EVENTS (
    EVENT_ID STRING,
    EVENT_TYPE STRING,
    TS TIMESTAMP_NTZ,
    PLAYER_ID STRING,
    PAYLOAD VARIANT
);

CREATE TABLE IF NOT EXISTS SNOWPITCH.BRONZE.LIVE_CONFIG (
    K STRING,
    V STRING
);
