CREATE OR REPLACE VIEW SNOWPITCH.SILVER.PLAYERS AS
SELECT
    PLAYER_ID,
    PAYLOAD:display_name::STRING AS DISPLAY_NAME,
    PAYLOAD:nation::STRING AS NATION,
    PAYLOAD:ovr::NUMBER AS OVR,
    PAYLOAD:spend_tier::STRING AS SPEND_TIER,
    PAYLOAD:lifetime_spend::FLOAT AS LIFETIME_SPEND,
    COALESCE(PAYLOAD:bot::BOOLEAN, FALSE) AS BOT
FROM SNOWPITCH.BRONZE.RAW_EVENTS
WHERE EVENT_TYPE = 'player_snapshot';

CREATE OR REPLACE VIEW SNOWPITCH.SILVER.MATCHES AS
SELECT
    PAYLOAD:match_id::STRING AS MATCH_ID,
    TS,
    PAYLOAD:home_id::STRING AS HOME_ID,
    PAYLOAD:away_id::STRING AS AWAY_ID,
    PAYLOAD:home_goals::NUMBER AS HOME_GOALS,
    PAYLOAD:away_goals::NUMBER AS AWAY_GOALS,
    PAYLOAD:home_spend_tier::STRING AS HOME_SPEND_TIER,
    PAYLOAD:away_spend_tier::STRING AS AWAY_SPEND_TIER,
    PAYLOAD:home_ovr::NUMBER AS HOME_OVR,
    PAYLOAD:away_ovr::NUMBER AS AWAY_OVR,
    PAYLOAD:winner_id::STRING AS WINNER_ID,
    PAYLOAD:patch::STRING AS PATCH,
    PAYLOAD:mode::STRING AS MODE
FROM SNOWPITCH.BRONZE.RAW_EVENTS
WHERE EVENT_TYPE = 'match_end';

CREATE OR REPLACE VIEW SNOWPITCH.SILVER.CHANCES AS
SELECT
    PAYLOAD:match_id::STRING AS MATCH_ID,
    PAYLOAD:chance_id::STRING AS CHANCE_ID,
    TS,
    PLAYER_ID AS ATTACKER_ID,
    PAYLOAD:minute::NUMBER AS MINUTE,
    PAYLOAD:attacking_home::BOOLEAN AS ATTACKING_HOME,
    PAYLOAD:trailing_before::BOOLEAN AS TRAILING_BEFORE,
    PAYLOAD:late::BOOLEAN AS LATE,
    PAYLOAD:timing::FLOAT AS TIMING,
    PAYLOAD:patch::STRING AS PATCH
FROM SNOWPITCH.BRONZE.RAW_EVENTS
WHERE EVENT_TYPE = 'chance';

CREATE OR REPLACE VIEW SNOWPITCH.SILVER.GOALS AS
SELECT
    PAYLOAD:match_id::STRING AS MATCH_ID,
    PAYLOAD:chance_id::STRING AS CHANCE_ID,
    TS,
    PLAYER_ID AS SCORER_ID,
    PAYLOAD:minute::NUMBER AS MINUTE,
    PAYLOAD:late::BOOLEAN AS LATE,
    PAYLOAD:trailing_before::BOOLEAN AS TRAILING_BEFORE,
    PAYLOAD:patch::STRING AS PATCH
FROM SNOWPITCH.BRONZE.RAW_EVENTS
WHERE EVENT_TYPE = 'goal';

CREATE OR REPLACE VIEW SNOWPITCH.SILVER.PACKS AS
SELECT
    PAYLOAD:pack_id::STRING AS PACK_ID,
    TS,
    PLAYER_ID,
    PAYLOAD:pack_type::STRING AS PACK_TYPE,
    PAYLOAD:advertised_rare_rate::FLOAT AS ADVERTISED_RARE_RATE,
    PAYLOAD:observed_rare::BOOLEAN AS OBSERVED_RARE,
    PAYLOAD:rarity::STRING AS RARITY,
    PAYLOAD:ovr::NUMBER AS OVR,
    PAYLOAD:patch::STRING AS PATCH
FROM SNOWPITCH.BRONZE.RAW_EVENTS
WHERE EVENT_TYPE = 'pack_open';

CREATE OR REPLACE VIEW SNOWPITCH.SILVER.TRADES AS
SELECT
    PAYLOAD:trade_id::STRING AS TRADE_ID,
    TS,
    PAYLOAD:seller_id::STRING AS SELLER_ID,
    PAYLOAD:buyer_id::STRING AS BUYER_ID,
    PAYLOAD:card_id::STRING AS CARD_ID,
    PAYLOAD:rarity::STRING AS RARITY,
    PAYLOAD:price::NUMBER AS PRICE,
    PAYLOAD:median_ref::NUMBER AS MEDIAN_REF,
    PAYLOAD:seconds_listed::NUMBER AS SECONDS_LISTED,
    PAYLOAD:wash::BOOLEAN AS WASH,
    PAYLOAD:patch::STRING AS PATCH
FROM SNOWPITCH.BRONZE.RAW_EVENTS
WHERE EVENT_TYPE = 'market_sale';
