CREATE OR REPLACE TABLE SNOWPITCH.GOLD.MATCH_FAIRNESS AS
WITH late AS (
    SELECT
        PATCH,
        COUNT_IF(LATE AND TRAILING_BEFORE) AS TRAILING_LATE_CHANCES,
        COUNT_IF(LATE AND TRAILING_BEFORE AND CHANCE_ID IN (SELECT CHANCE_ID FROM SNOWPITCH.SILVER.GOALS)) AS TRAILING_LATE_GOALS
    FROM SNOWPITCH.SILVER.CHANCES
    GROUP BY PATCH
),
spend AS (
    SELECT HOME_SPEND_TIER AS SPEND_TIER, COUNT(*) AS N,
           COUNT_IF(WINNER_ID = HOME_ID) AS WINS
    FROM SNOWPITCH.SILVER.MATCHES GROUP BY 1
    UNION ALL
    SELECT AWAY_SPEND_TIER, COUNT(*),
           COUNT_IF(WINNER_ID = AWAY_ID)
    FROM SNOWPITCH.SILVER.MATCHES GROUP BY 1
),
spend_agg AS (
    SELECT SPEND_TIER, SUM(N) AS MATCHES, SUM(WINS) AS WINS,
           SUM(WINS) * 1.0 / NULLIF(SUM(N), 0) AS WIN_RATE
    FROM spend GROUP BY 1
)
SELECT
    l.PATCH,
    l.TRAILING_LATE_CHANCES,
    l.TRAILING_LATE_GOALS,
    l.TRAILING_LATE_GOALS / NULLIF(l.TRAILING_LATE_CHANCES, 0) AS LATE_COMEBACK_RATE,
    (SELECT WIN_RATE FROM spend_agg WHERE SPEND_TIER = 'whale') AS WHALE_WIN_RATE,
    (SELECT WIN_RATE FROM spend_agg WHERE SPEND_TIER = 'f2p') AS F2P_WIN_RATE
FROM late l;

CREATE OR REPLACE TABLE SNOWPITCH.GOLD.PACK_ODDS AS
SELECT
    PATCH,
    COUNT(*) AS PACKS,
    AVG(IFF(OBSERVED_RARE, 1, 0)) AS OBSERVED_RARE_RATE,
    AVG(ADVERTISED_RARE_RATE) AS ADVERTISED_RARE_RATE,
    OBSERVED_RARE_RATE - ADVERTISED_RARE_RATE AS DRIFT,
    POWER(SUM(IFF(OBSERVED_RARE, 1, 0)) - COUNT(*) * 0.12, 2) / (COUNT(*) * 0.12) AS CHI_SQUARE_STAT
FROM SNOWPITCH.SILVER.PACKS
GROUP BY PATCH;

CREATE OR REPLACE TABLE SNOWPITCH.GOLD.MARKET_HEALTH AS
SELECT
    PATCH,
    COUNT(*) AS TRADES,
    MEDIAN(PRICE) AS MEDIAN_PRICE,
    AVG(PRICE) AS AVG_PRICE,
    COUNT_IF(PRICE > MEDIAN_REF * 6 AND SECONDS_LISTED < 120) AS SUSPECTED_WASH,
    COUNT(DISTINCT IFF(PRICE > MEDIAN_REF * 6 AND SECONDS_LISTED < 120, SELLER_ID, NULL)) AS WASH_ACCOUNTS
FROM SNOWPITCH.SILVER.TRADES
GROUP BY PATCH;

CREATE OR REPLACE TABLE SNOWPITCH.GOLD.DAILY AS
SELECT
    CAST(TS AS DATE) AS DAY,
    COUNT(DISTINCT MATCH_ID) AS MATCHES,
    COUNT(*) AS MATCH_ROWS
FROM SNOWPITCH.SILVER.MATCHES
GROUP BY 1
ORDER BY 1;

CREATE OR REPLACE TABLE SNOWPITCH.GOLD.SPEND AS
SELECT SPEND_TIER,
       COUNT(*) AS APPEARANCES,
       COUNT_IF(WINNER_ID = PID) AS WINS,
       COUNT_IF(WINNER_ID = PID) * 1.0 / NULLIF(COUNT(*), 0) AS WIN_RATE
FROM (
    SELECT HOME_ID AS PID, HOME_SPEND_TIER AS SPEND_TIER, WINNER_ID FROM SNOWPITCH.SILVER.MATCHES
    UNION ALL
    SELECT AWAY_ID, AWAY_SPEND_TIER, WINNER_ID FROM SNOWPITCH.SILVER.MATCHES
) t
GROUP BY 1
ORDER BY WIN_RATE DESC;

CREATE OR REPLACE TABLE SNOWPITCH.GOLD.INTEGRITY_ALERTS AS
SELECT 'momentum' AS ALERT_ID, 'high' AS SEVERITY,
       'Late comeback rate jumped after Whiteout' AS TITLE,
       'Trailing sides convert late chances much more often after Patch 1.12. This is the planted momentum bias.' AS DETAIL,
       LATE_COMEBACK_RATE AS METRIC
FROM SNOWPITCH.GOLD.MATCH_FAIRNESS
WHERE PATCH = '1.12-whiteout' AND LATE_COMEBACK_RATE >= 0.36
UNION ALL
SELECT 'pack_odds', 'high',
       'Advertised pack odds do not match observed rares',
       'Whiteout Rare packs still advertise 12% but observed rare rate collapsed. Chi-square is against the posted rate.',
       OBSERVED_RARE_RATE
FROM SNOWPITCH.GOLD.PACK_ODDS
WHERE PATCH = '1.12-whiteout' AND OBSERVED_RARE_RATE < 0.08
UNION ALL
SELECT 'coin_ring', 'critical',
       'Transfer market wash ring after the patch',
       'A tight set of accounts sells commons in under two minutes at 6–14× median. Classic coin-move pattern.',
       SUSPECTED_WASH
FROM SNOWPITCH.GOLD.MARKET_HEALTH
WHERE PATCH = '1.12-whiteout' AND SUSPECTED_WASH >= 20;
