-- Least-privilege roles for Snowpitch. Do not run the API as ACCOUNTADMIN.
--
-- Apply with an admin role after the database exists:
--   snowsql -f transform/snowflake/05_rbac.sql

USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWPITCH;

CREATE ROLE IF NOT EXISTS SNOWPITCH_LOADER;
CREATE ROLE IF NOT EXISTS SNOWPITCH_ANALYST;

GRANT USAGE ON DATABASE SNOWPITCH TO ROLE SNOWPITCH_LOADER;
GRANT USAGE ON DATABASE SNOWPITCH TO ROLE SNOWPITCH_ANALYST;

GRANT USAGE ON SCHEMA SNOWPITCH.BRONZE TO ROLE SNOWPITCH_LOADER;
GRANT USAGE ON SCHEMA SNOWPITCH.SILVER TO ROLE SNOWPITCH_LOADER;
GRANT USAGE ON SCHEMA SNOWPITCH.GOLD TO ROLE SNOWPITCH_LOADER;

GRANT USAGE ON SCHEMA SNOWPITCH.BRONZE TO ROLE SNOWPITCH_ANALYST;
GRANT USAGE ON SCHEMA SNOWPITCH.SILVER TO ROLE SNOWPITCH_ANALYST;
GRANT USAGE ON SCHEMA SNOWPITCH.GOLD TO ROLE SNOWPITCH_ANALYST;

-- Loader: write bronze, read everything (needed for live ingest + refresh).
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA SNOWPITCH.BRONZE
    TO ROLE SNOWPITCH_LOADER;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWPITCH.SILVER TO ROLE SNOWPITCH_LOADER;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWPITCH.GOLD TO ROLE SNOWPITCH_LOADER;
GRANT SELECT ON ALL VIEWS IN SCHEMA SNOWPITCH.SILVER TO ROLE SNOWPITCH_LOADER;
GRANT SELECT ON ALL VIEWS IN SCHEMA SNOWPITCH.GOLD TO ROLE SNOWPITCH_LOADER;
GRANT USAGE ON ALL STAGES IN SCHEMA SNOWPITCH.BRONZE TO ROLE SNOWPITCH_LOADER;

-- Analyst: read-only gold/silver for the LiveOps board and ad-hoc SQL.
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWPITCH.SILVER TO ROLE SNOWPITCH_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWPITCH.GOLD TO ROLE SNOWPITCH_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA SNOWPITCH.SILVER TO ROLE SNOWPITCH_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA SNOWPITCH.GOLD TO ROLE SNOWPITCH_ANALYST;
GRANT SELECT ON SNOWPITCH.BRONZE.RAW_EVENTS TO ROLE SNOWPITCH_ANALYST;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SNOWPITCH_LOADER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SNOWPITCH_ANALYST;

-- Future objects.
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SNOWPITCH.BRONZE
    TO ROLE SNOWPITCH_LOADER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SNOWPITCH.GOLD TO ROLE SNOWPITCH_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SNOWPITCH.GOLD TO ROLE SNOWPITCH_ANALYST;
